modLoader = "javafml"
loaderVersion = "[36,)"
license = "All rights reserved"
issueTrackerURL = "https://github.com/Seniorendi/AdvancedPeripherals/issues"
logoFile = "pack.png"
[[mods]]
modId = "advancedperipherals"
version = "0.6.5b"
displayName = "Advanced Peripherals"
displayURL = "https://docs.srendi.de/"
authors = "Srendi"
description = '''
Advanced Peripherals is a mod that adds many useful extensions for CC:Tweaked(Computercraft).
You can communicate with Rerfined Storage, Applied Energistics 2 or with the whole Minecraft world.
Adds things like the Me Bridge, various types of turtles, the Chat Box and more.
'''
[[dependencies.advancedperipherals]]
modId = "forge"
mandatory = true
versionRange = "[36.0.46,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.advancedperipherals]]
modId = "minecraft"
mandatory = true
versionRange = "1.16.5"
ordering = "NONE"
side = "BOTH"
[[dependencies.advancedperipherals]]
modId = "computercraft"
mandatory = true
versionRange = "1.96.0"
ordering = "NONE"
side = "BOTH"
[[dependencies.advancedperipherals]]
modId = "curios"
mandatory = false
versionRange = "[1.16.5-4.0.5.1,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.advancedperipherals]]
modId = "appliedenergistics2"
mandatory = false
versionRange = "8.2.0"
ordnering = "NONE"
side = "BOTH"
[[dependencies.advancedperipherals]]
modId = "refinedstorage"
mandatory = false
versionRange = "[1.9.12,)"
ordnering = "NONE"
side = "BOTH"