modLoader = "javafml"
loaderVersion = "[40,)"
license = "All rights reserved"
issueTrackerURL = "https://github.com/Seniorendi/AdvancedPeripherals/issues"
logoFile = "pack.png"
[[mods]]
modId = "advancedperipherals"
version = "${file.jarVersion}"
displayName = "Advanced Peripherals"
displayURL = "https://docs.srendi.de/"
authors = "Srendi"
description = '''
Advanced Peripherals is a mod that adds many useful extensions for CC:Tweaked(Computercraft).
You can communicate with Rerfined Storage, Applied Energistics 2 or with the whole Minecraft world.
Adds things like the Me Bridge, various types of turtles, the Chat Box and more.
'''
[[dependencies.advancedperipherals]]
modId = "forge"
mandatory = true
versionRange = "[40.1.52,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.advancedperipherals]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.advancedperipherals]]
modId = "computercraft"
mandatory = true
versionRange = "[1.100.4,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.advancedperipherals]]
modId = "curios"
mandatory = false
versionRange = "[1.18-5.0.2.3,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.advancedperipherals]]
modId = "ae2"
mandatory = false
versionRange = "[11.0.0-alpha.6,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.advancedperipherals]]
modId = "refinedstorage"
mandatory = false
versionRange = "[1.10.2,)"
ordnering = "NONE"
side = "BOTH"
[[dependencies.advancedperipherals]]
modId = "minecolonies"
mandatory = false
versionRange = "[1.18.2-1.0.877-BETA,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.advancedperipherals]]
modId = "curios"
mandatory = false
versionRange = "[1.18.2-1.0.578-ALPHA,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.advancedperipherals]]
modId = "patchouli"
mandatory = false
versionRange = "[1.18.2-67,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.advancedperipherals]]
modId = "create"
mandatory = false
versionRange = "[0.5.1,)"
ordering = "NONE"
side = "BOTH"